import Layout from "@/components/Layout";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { TitleContext } from "@/TitleContext";
import { useState } from "react";
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: false,
    },
  },
});
export default function App({
  Component,

  pageProps: { session, ...pageProps },
}: AppProps) {
  const [title, setTitle] = useState("untitled-document.md");
  const [content, setContent] = useState("");
  return (
    <SessionProvider session={session}>
      <TitleContext.Provider value={{ title, setTitle, content, setContent }}>
        <QueryClientProvider client={queryClient}>
          <Layout>
            <Head>
              <title>Frontend Mentor | In-browser markdown editor</title>
              <meta name="description" content="Generated by create next app" />
              <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
              />
              <link rel="icon" href="/favicon.png" />
            </Head>
            <Component {...pageProps} />
          </Layout>
        </QueryClientProvider>
      </TitleContext.Provider>
    </SessionProvider>
  );
}
