import Typography from "@/components/Typography";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
export default function Home() {
  const { data } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (
      data?.user?.documents !== undefined &&
      data?.user?.documents.length > 0
    ) {
      router.push(`/document/${data?.user?.documents[0].id}`);
    } else {
      router.push(`/document/new`);
    }
  }, [data]);

  return (
    <>
      <Head>
        <title>Frontend Mentor | In-browser markdown editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    </>
  );
}
